# Color support
set-option -ga terminal-overrides ",*-256color:Tc"
set-environment -g COLORTERM truecolor

# History limit
set-option -g history-limit 90000

# Extended keys are needed for certain TUIs
set-option -g extend-keys on
set-option -g extended-keys-format csi-u

# Make sure focus events are relayed correctly
set-option -g focus-events on